version: '3.8'

services:

  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - .:/workspace:cached
    depends_on:
      - database
    command: sleep infinity

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: classicmodels
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d

  database-management:
    image: linuxserver/mysql-workbench:latest
    environment:
      - TZ=Etc/UTC
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      # Persisting workbench configuration for development 
      # See https://dev.mysql.com/doc/workbench/en/wb-configuring-files.html
      - ./database/workbench:/config/.mysql/workbench
    depends_on:
      - database

#   ollama:
#     container_name: ollama
#     image: ollama/ollama:0.1.27
#     ports:
#       - "11434:11434"
#     volumes:
#       - ollama:/root/.ollama
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: 1
#               capabilities: [gpu]

# volumes:
#   ollama: