version: '3.8'

services:

  app:
    build: 
      context: ./app
    environment:
      DATABASE_URI: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_SCHEMA}
      LLM_URL: ${LLM_URL}
      LLM_MODEL: ${LLM_MODEL}
    volumes:
      - .:/workspace:cached
    depends_on:
      - database
    command: sleep infinity

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_SCHEMA}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d

  database-management:
    image: linuxserver/mysql-workbench:latest
    environment:
      - TZ=Etc/UTC
    ports:
      # TODO figure out what each of these is for
      - 3000:3000
      - 3001:3001
    volumes:
      # Persisting workbench configuration for development 
      # See https://dev.mysql.com/doc/workbench/en/wb-configuring-files.html
      - ./database/workbench:/config/.mysql/workbench
    depends_on:
      - database

#   ollama:
#     container_name: ollama
#     image: ollama/ollama:0.1.27
#     ports:
#       - "11434:11434"
#     volumes:
#       - ollama:/root/.ollama
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: 1
#               capabilities: [gpu]

# volumes:
#   ollama: